on:
  pull_request:
    types: [closed]
permissions:
  contents: write
  issues: write
jobs:
  remove-comments:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Remove Temporary Comments
      run: |
        find . -type f -name '*.go' -exec sed -i '/\/\/ TEMP:/d' {} +
    - name: Commit Changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git commit -am "Remove temporary comments"
        git push
